"
I represent Fortran Backspace statement


"
Class {
	#name : 'FASTFortranBackspaceStatement',
	#superclass : 'FASTFortranAbstractIOStatement',
	#category : 'FAST-Fortran-Entities-Entities',
	#package : 'FAST-Fortran-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortranBackspaceStatement class >> annotation [

	<FMClass: #BackspaceStatement super: #FASTFortranAbstractIOStatement>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
