"
I represent Fortran Arithmetic Double Precision Literal (Constant)


"
Class {
	#name : #FASTFortranDoublePrecisionLiteral,
	#superclass : #FASTFortranNumericalConstant,
	#category : #'FAST-Fortran-Entities-Entities'
}

{ #category : #meta }
FASTFortranDoublePrecisionLiteral class >> annotation [

	<FMClass: #DoublePrecisionLiteral super: #FASTFortranNumericalConstant>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
