"
I represent Fortran accept statement


"
Class {
	#name : 'FASTFortranAcceptStatement',
	#superclass : 'FASTFortranAbstractStatement',
	#category : 'FAST-Fortran-Entities-Entities',
	#package : 'FAST-Fortran-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortranAcceptStatement class >> annotation [

	<FMClass: #AcceptStatement super: #FASTFortranAbstractStatement>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
