"
I represent Fortran NameList statement [not implemented yet]


"
Class {
	#name : #FASTFortranNameListStatement,
	#superclass : #FASTFortranAbstractStatement,
	#category : #'FAST-Fortran-Entities-Entities'
}

{ #category : #meta }
FASTFortranNameListStatement class >> annotation [

	<FMClass: #NameListStatement super: #FASTFortranAbstractStatement>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
