"
I represent Fortran End File statement


"
Class {
	#name : 'FASTFortranEndFileStatement',
	#superclass : 'FASTFortranAbstractIOStatement',
	#category : 'FAST-Fortran-Entities-Entities',
	#package : 'FAST-Fortran-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortranEndFileStatement class >> annotation [

	<FMClass: #EndFileStatement super: #FASTFortranAbstractIOStatement>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
