"
I represent Fortran Else statement


"
Class {
	#name : 'FASTFortranElseStatement',
	#superclass : 'FASTFortranAbstractStatement',
	#category : 'FAST-Fortran-Entities-Entities',
	#package : 'FAST-Fortran-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortranElseStatement class >> annotation [

	<FMClass: #ElseStatement super: #FASTFortranAbstractStatement>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
