"
I represent Fortran Arithmetic Double Complex Literal (Constant)


"
Class {
	#name : #FASTFortranDoubleComplexLiteral,
	#superclass : #FASTFortranNumericalConstant,
	#category : #'FAST-Fortran-Entities-Entities'
}

{ #category : #meta }
FASTFortranDoubleComplexLiteral class >> annotation [

	<FMClass: #DoubleComplexLiteral super: #FASTFortranNumericalConstant>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
