"
I represent a fortran subprogram: procedure or block data


"
Class {
	#name : 'FASTFortranSubprogram',
	#superclass : 'FASTFortranProgramUnit',
	#category : 'FAST-Fortran-Entities-Entities',
	#package : 'FAST-Fortran-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortranSubprogram class >> annotation [

	<FMClass: #Subprogram super: #FASTFortranProgramUnit>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
