"
I represent Fortran Do While statement


"
Class {
	#name : 'FASTFortranDoWhileStatement',
	#superclass : 'FASTFortranConditionalStatement',
	#category : 'FAST-Fortran-Entities-Entities',
	#package : 'FAST-Fortran-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortranDoWhileStatement class >> annotation [

	<FMClass: #DoWhileStatement super: #FASTFortranConditionalStatement>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
