"
The logical IF statement executes one single statement, or does not execute it, depending on the value of a logical expression.


"
Class {
	#name : 'FASTFortranIfLogicalStatement',
	#superclass : 'FASTFortranConditionalStatement',
	#category : 'FAST-Fortran-Entities-Entities',
	#package : 'FAST-Fortran-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortranIfLogicalStatement class >> annotation [

	<FMClass: #IfLogicalStatement super: #FASTFortranConditionalStatement>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
