"
I represent Fortran Substring


"
Class {
	#name : 'FASTFortranSubstring',
	#superclass : 'FASTFortranAbstractExpression',
	#category : 'FAST-Fortran-Entities-Entities',
	#package : 'FAST-Fortran-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortranSubstring class >> annotation [

	<FMClass: #Substring super: #FASTFortranAbstractExpression>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
