"
I represent Fortran Integer type


"
Class {
	#name : 'FASTFortranIntegerType',
	#superclass : 'FASTFortranType',
	#category : 'FAST-Fortran-Entities-Entities',
	#package : 'FAST-Fortran-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortranIntegerType class >> annotation [

	<FMClass: #IntegerType super: #FASTFortranType>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
