"
I represent Fortran Double Precision type, synonym of REAL*8


"
Class {
	#name : 'FASTFortranDoublePrecisionType',
	#superclass : 'FASTFortranType',
	#category : 'FAST-Fortran-Entities-Entities',
	#package : 'FAST-Fortran-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortranDoublePrecisionType class >> annotation [

	<FMClass: #DoublePrecisionType super: #FASTFortranType>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
