"
I represent Fortran Union statement


"
Class {
	#name : 'FASTFortranUnionStatement',
	#superclass : 'FASTFortranAbstractStatement',
	#category : 'FAST-Fortran-Entities-Entities',
	#package : 'FAST-Fortran-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortranUnionStatement class >> annotation [

	<FMClass: #UnionStatement super: #FASTFortranAbstractStatement>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
