"
I represent Fortran Close statement


"
Class {
	#name : 'FASTFortranCloseStatement',
	#superclass : 'FASTFortranAbstractIOStatement',
	#category : 'FAST-Fortran-Entities-Entities',
	#package : 'FAST-Fortran-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortranCloseStatement class >> annotation [

	<FMClass: #CloseStatement super: #FASTFortranAbstractIOStatement>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
