"
I represent Fortran Arithmetic Double Precision Literal (Constant)


"
Class {
	#name : 'FASTFortranDoublePrecisionLiteral',
	#superclass : 'FASTFortranNumericalConstant',
	#category : 'FAST-Fortran-Entities-Entities',
	#package : 'FAST-Fortran-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortranDoublePrecisionLiteral class >> annotation [

	<FMClass: #DoublePrecisionLiteral super: #FASTFortranNumericalConstant>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
