"
I represent Fortran Map statement


"
Class {
	#name : 'FASTFortranMapStatement',
	#superclass : 'FASTFortranAbstractStatement',
	#category : 'FAST-Fortran-Entities-Entities',
	#package : 'FAST-Fortran-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortranMapStatement class >> annotation [

	<FMClass: #MapStatement super: #FASTFortranAbstractStatement>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
