"
I represent a virtual UNDEFINED type that can be used in a IMPLICIT UNDEFINED statement


"
Class {
	#name : #FASTFortranImplicitUndefinedType,
	#superclass : #FASTFortranType,
	#category : #'FAST-Fortran-Entities-Entities'
}

{ #category : #meta }
FASTFortranImplicitUndefinedType class >> annotation [

	<FMClass: #ImplicitUndefinedType super: #FASTFortranType>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
