"
I represent Fortran DECODE statement


"
Class {
	#name : 'FASTFortranDecodeStatement',
	#superclass : 'FASTFortranAbstractIOStatement',
	#category : 'FAST-Fortran-Entities-Entities',
	#package : 'FAST-Fortran-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortranDecodeStatement class >> annotation [

	<FMClass: #DecodeStatement super: #FASTFortranAbstractIOStatement>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
