"
I represent Fortran Arithmetic Complex Literal (Constant)


"
Class {
	#name : 'FASTFortranComplexLiteral',
	#superclass : 'FASTFortranNumericalConstant',
	#category : 'FAST-Fortran-Entities-Entities',
	#package : 'FAST-Fortran-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortranComplexLiteral class >> annotation [

	<FMClass: #ComplexLiteral super: #FASTFortranNumericalConstant>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
