"
I represent Fortran Character Literal


"
Class {
	#name : 'FASTFortranCharacterType',
	#superclass : 'FASTFortranType',
	#category : 'FAST-Fortran-Entities-Entities',
	#package : 'FAST-Fortran-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortranCharacterType class >> annotation [

	<FMClass: #CharacterType super: #FASTFortranType>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
