"
I represent Fortran Arithmetic Complex Literal (Constant)


"
Class {
	#name : #FASTFortranComplexLiteral,
	#superclass : #FASTFortranNumericalConstant,
	#category : #'FAST-Fortran-Entities-Entities'
}

{ #category : #meta }
FASTFortranComplexLiteral class >> annotation [

	<FMClass: #ComplexLiteral super: #FASTFortranNumericalConstant>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
