"
I represent Fortran Continue statement


"
Class {
	#name : 'FASTFortranContinueStatement',
	#superclass : 'FASTFortranAbstractStatement',
	#category : 'FAST-Fortran-Entities-Entities',
	#package : 'FAST-Fortran-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortranContinueStatement class >> annotation [

	<FMClass: #ContinueStatement super: #FASTFortranAbstractStatement>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
