"
A virtual entity representing all the content of an included file


"
Class {
	#name : 'FASTFortranIncludedFile',
	#superclass : 'FASTFortranProgramUnit',
	#category : 'FAST-Fortran-Entities-Entities',
	#package : 'FAST-Fortran-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortranIncludedFile class >> annotation [

	<FMClass: #IncludedFile super: #FASTFortranProgramUnit>
	<package: #'FAST-Fortran-Entities'>
	<generated>
	^ self
]
